# Generated by Django 2.1.7 on 2019-03-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
