# Generated by Django 2.1.7 on 2019-03-20 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='uon',
            new_name='uom',
        ),
    ]
